"""init

Revision ID: 262d4fc8ae9e
Revises: 
Create Date: 2022-05-06 02:42:50.817969

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '262d4fc8ae9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('songs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('album_id')
    )
    op.create_index(op.f('ix_album_album_name'), 'album', ['album_name'], unique=False)
    op.create_index(op.f('ix_album_author'), 'album', ['author'], unique=False)
    op.create_index(op.f('ix_album_thumbnail_path'), 'album', ['thumbnail_path'], unique=False)
    op.create_table('song',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('song_id')
    )
    op.create_index(op.f('ix_song_artist'), 'song', ['artist'], unique=False)
    op.create_index(op.f('ix_song_name'), 'song', ['name'], unique=False)
    op.create_index(op.f('ix_song_youtube_id'), 'song', ['youtube_id'], unique=False)
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('playlist',
    sa.Column('playlist_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('songs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('playlist_id')
    )
    op.create_index(op.f('ix_playlist_playlist_name'), 'playlist', ['playlist_name'], unique=False)
    op.create_index(op.f('ix_playlist_thumbnail_path'), 'playlist', ['thumbnail_path'], unique=False)
    op.create_index(op.f('ix_playlist_user_id'), 'playlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_user_id'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_thumbnail_path'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_playlist_name'), table_name='playlist')
    op.drop_table('playlist')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_song_youtube_id'), table_name='song')
    op.drop_index(op.f('ix_song_name'), table_name='song')
    op.drop_index(op.f('ix_song_artist'), table_name='song')
    op.drop_table('song')
    op.drop_index(op.f('ix_album_thumbnail_path'), table_name='album')
    op.drop_index(op.f('ix_album_author'), table_name='album')
    op.drop_index(op.f('ix_album_album_name'), table_name='album')
    op.drop_table('album')
    # ### end Alembic commands ###
