"""schema_test

Revision ID: 746f025c3b12
Revises: 99694cde7dc7
Create Date: 2022-05-12 06:17:55.958410

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '746f025c3b12'
down_revision = '99694cde7dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testtable', schema='test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testtable',
    sa.Column('test_id', sa.INTEGER(), server_default=sa.text("nextval('test.testtable_test_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('test_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_test_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('test_id', name='testtable_pkey'),
    schema='test'
    )
    # ### end Alembic commands ###
