"""schema_test

Revision ID: 99694cde7dc7
Revises: fe645faf423b
Create Date: 2022-05-12 06:15:03.184144

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '99694cde7dc7'
down_revision = 'fe645faf423b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testtable', sa.Column('full_test_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testtable', 'full_test_name', schema='test')
    # ### end Alembic commands ###
