"""added_video

Revision ID: b712779e6c86
Revises: fa775cea1edb
Create Date: 2022-05-12 07:05:19.081382

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'b712779e6c86'
down_revision = 'fa775cea1edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('youtube_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('video_id'),
    schema='videos'
    )
    op.create_index(op.f('ix_videos_video_creator'), 'video', ['creator'], unique=False, schema='videos')
    op.create_index(op.f('ix_videos_video_name'), 'video', ['name'], unique=False, schema='videos')
    op.create_index(op.f('ix_videos_video_youtube_id'), 'video', ['youtube_id'], unique=False, schema='videos')
    op.alter_column('song', 'youtube_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='songs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('song', 'youtube_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='songs')
    op.drop_index(op.f('ix_videos_video_youtube_id'), table_name='video', schema='videos')
    op.drop_index(op.f('ix_videos_video_name'), table_name='video', schema='videos')
    op.drop_index(op.f('ix_videos_video_creator'), table_name='video', schema='videos')
    op.drop_table('video', schema='videos')
    # ### end Alembic commands ###
