"""schema_test

Revision ID: cca27662a314
Revises: 746f025c3b12
Create Date: 2022-05-12 06:24:08.273479

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'cca27662a314'
down_revision = '746f025c3b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('songs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('album_id'),
    schema='songs'
    )
    op.create_index(op.f('ix_songs_album_album_name'), 'album', ['album_name'], unique=False, schema='songs')
    op.create_index(op.f('ix_songs_album_author'), 'album', ['author'], unique=False, schema='songs')
    op.create_index(op.f('ix_songs_album_thumbnail_path'), 'album', ['thumbnail_path'], unique=False, schema='songs')
    op.create_table('song',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('song_id'),
    schema='songs'
    )
    op.create_index(op.f('ix_songs_song_artist'), 'song', ['artist'], unique=False, schema='songs')
    op.create_index(op.f('ix_songs_song_name'), 'song', ['name'], unique=False, schema='songs')
    op.create_index(op.f('ix_songs_song_youtube_id'), 'song', ['youtube_id'], unique=False, schema='songs')
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_user_username'), 'user', ['username'], unique=False, schema='users')
    op.create_table('playlist',
    sa.Column('playlist_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('songs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.user_id'], ),
    sa.PrimaryKeyConstraint('playlist_id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_playlist_playlist_name'), 'playlist', ['playlist_name'], unique=False, schema='users')
    op.create_index(op.f('ix_users_playlist_thumbnail_path'), 'playlist', ['thumbnail_path'], unique=False, schema='users')
    op.create_index(op.f('ix_users_playlist_user_id'), 'playlist', ['user_id'], unique=False, schema='users')
    op.drop_index('ix_playlist_playlist_name', table_name='playlist')
    op.drop_index('ix_playlist_thumbnail_path', table_name='playlist')
    op.drop_index('ix_playlist_user_id', table_name='playlist')
    op.drop_table('playlist')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_song_artist', table_name='song')
    op.drop_index('ix_song_name', table_name='song')
    op.drop_index('ix_song_youtube_id', table_name='song')
    op.drop_table('song')
    op.drop_index('ix_album_album_name', table_name='album')
    op.drop_index('ix_album_author', table_name='album')
    op.drop_index('ix_album_thumbnail_path', table_name='album')
    op.drop_table('album')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('album_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('songs', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('album_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('thumbnail_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('album_id', name='album_pkey')
    )
    op.create_index('ix_album_thumbnail_path', 'album', ['thumbnail_path'], unique=False)
    op.create_index('ix_album_author', 'album', ['author'], unique=False)
    op.create_index('ix_album_album_name', 'album', ['album_name'], unique=False)
    op.create_table('song',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artist', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('song_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('youtube_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('song_id', name='song_pkey')
    )
    op.create_index('ix_song_youtube_id', 'song', ['youtube_id'], unique=False)
    op.create_index('ix_song_name', 'song', ['name'], unique=False)
    op.create_index('ix_song_artist', 'song', ['artist'], unique=False)
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('user_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.create_table('playlist',
    sa.Column('playlist_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('songs', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('playlist_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('thumbnail_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='playlist_user_id_fkey'),
    sa.PrimaryKeyConstraint('playlist_id', name='playlist_pkey')
    )
    op.create_index('ix_playlist_user_id', 'playlist', ['user_id'], unique=False)
    op.create_index('ix_playlist_thumbnail_path', 'playlist', ['thumbnail_path'], unique=False)
    op.create_index('ix_playlist_playlist_name', 'playlist', ['playlist_name'], unique=False)
    op.drop_index(op.f('ix_users_playlist_user_id'), table_name='playlist', schema='users')
    op.drop_index(op.f('ix_users_playlist_thumbnail_path'), table_name='playlist', schema='users')
    op.drop_index(op.f('ix_users_playlist_playlist_name'), table_name='playlist', schema='users')
    op.drop_table('playlist', schema='users')
    op.drop_index(op.f('ix_users_user_username'), table_name='user', schema='users')
    op.drop_table('user', schema='users')
    op.drop_index(op.f('ix_songs_song_youtube_id'), table_name='song', schema='songs')
    op.drop_index(op.f('ix_songs_song_name'), table_name='song', schema='songs')
    op.drop_index(op.f('ix_songs_song_artist'), table_name='song', schema='songs')
    op.drop_table('song', schema='songs')
    op.drop_index(op.f('ix_songs_album_thumbnail_path'), table_name='album', schema='songs')
    op.drop_index(op.f('ix_songs_album_author'), table_name='album', schema='songs')
    op.drop_index(op.f('ix_songs_album_album_name'), table_name='album', schema='songs')
    op.drop_table('album', schema='songs')
    # ### end Alembic commands ###
