"""schema_test

Revision ID: fa775cea1edb
Revises: cca27662a314
Create Date: 2022-05-12 06:26:07.370528

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'fa775cea1edb'
down_revision = 'cca27662a314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='songs')
    op.create_index(op.f('ix_songs_album_album_id'), 'album', ['album_id'], unique=False, schema='songs')
    op.create_index(op.f('ix_songs_album_year'), 'album', ['year'], unique=False, schema='songs')
    op.create_index(op.f('ix_users_user_user_id'), 'user', ['user_id'], unique=False, schema='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_user_id'), table_name='user', schema='users')
    op.drop_index(op.f('ix_songs_album_year'), table_name='album', schema='songs')
    op.drop_index(op.f('ix_songs_album_album_id'), table_name='album', schema='songs')
    op.drop_column('album', 'description', schema='songs')
    # ### end Alembic commands ###
