"""test

Revision ID: 9c4ca7eb4fa2
Revises: 3f0ae629ccf2
Create Date: 2022-05-01 02:35:57.596287

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9c4ca7eb4fa2'
down_revision = '3f0ae629ccf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('song_id'),
    schema='music'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song', schema='music')
    # ### end Alembic commands ###
