"""init

Revision ID: 9e2f2e199670
Revises: 
Create Date: 2022-05-01 19:08:34.641596

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9e2f2e199670'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('song_id'),
    schema='music'
    )
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='users'
    )
    op.create_table('playlist',
    sa.Column('playlist_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('songs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.user_id'], ),
    sa.PrimaryKeyConstraint('playlist_id'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist', schema='users')
    op.drop_table('user', schema='users')
    op.drop_table('song', schema='music')
    # ### end Alembic commands ###
