"""init

Revision ID: ccac73d7c448
Revises: 
Create Date: 2022-05-02 02:34:10.367993

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ccac73d7c448'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('album_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('songs', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('album_id'),
    schema='music'
    )
    op.create_index(op.f('ix_music_album_album_name'), 'album', ['album_name'], unique=False, schema='music')
    op.create_index(op.f('ix_music_album_author'), 'album', ['author'], unique=False, schema='music')
    op.create_index(op.f('ix_music_album_thumbnail_path'), 'album', ['thumbnail_path'], unique=False, schema='music')
    op.create_table('song',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('song_id'),
    schema='music'
    )
    op.create_index(op.f('ix_music_song_artist'), 'song', ['artist'], unique=False, schema='music')
    op.create_index(op.f('ix_music_song_name'), 'song', ['name'], unique=False, schema='music')
    op.create_index(op.f('ix_music_song_youtube_id'), 'song', ['youtube_id'], unique=False, schema='music')
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_user_username'), 'user', ['username'], unique=False, schema='users')
    op.create_table('playlist',
    sa.Column('playlist_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('songs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.user_id'], ),
    sa.PrimaryKeyConstraint('playlist_id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_playlist_playlist_name'), 'playlist', ['playlist_name'], unique=False, schema='users')
    op.create_index(op.f('ix_users_playlist_thumbnail_path'), 'playlist', ['thumbnail_path'], unique=False, schema='users')
    op.create_index(op.f('ix_users_playlist_user_id'), 'playlist', ['user_id'], unique=False, schema='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_playlist_user_id'), table_name='playlist', schema='users')
    op.drop_index(op.f('ix_users_playlist_thumbnail_path'), table_name='playlist', schema='users')
    op.drop_index(op.f('ix_users_playlist_playlist_name'), table_name='playlist', schema='users')
    op.drop_table('playlist', schema='users')
    op.drop_index(op.f('ix_users_user_username'), table_name='user', schema='users')
    op.drop_table('user', schema='users')
    op.drop_index(op.f('ix_music_song_youtube_id'), table_name='song', schema='music')
    op.drop_index(op.f('ix_music_song_name'), table_name='song', schema='music')
    op.drop_index(op.f('ix_music_song_artist'), table_name='song', schema='music')
    op.drop_table('song', schema='music')
    op.drop_index(op.f('ix_music_album_thumbnail_path'), table_name='album', schema='music')
    op.drop_index(op.f('ix_music_album_author'), table_name='album', schema='music')
    op.drop_index(op.f('ix_music_album_album_name'), table_name='album', schema='music')
    op.drop_table('album', schema='music')
    # ### end Alembic commands ###
